### ISSUE TITLE
Mousepointers

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/lxlite#8]
in the lxlite subdir are 3 mouse pointer sets. I really wonder what a mouse pointer has to do with lxlite at all.
I vote for removing those

**Comment by dmik** [comment]
I recall lxlite used to replace mouse pointers in PM or such. Are they referenced from anywhere?

**Comment by StevenLevine** [comment]
You are probably thinking of the SysIcons.exe utility, which ships with lxlite.  Lxlite.exe does not do the replacements.

**Comment by SilvanScherrer** [comment]
the mouse pointers are moved to their own directory in https://github.com/bitwiseworks/lxlite/commit/af73680f01c1b0dce265d73453bfabd5fd20b3c4. the installer will not ship them anymore
